package reqt {
  object abbrev { //TODO check against metamodel for missing entities
    def P(id: String) = reqt.Product(id)   
    def P(id: Int) = reqt.Product(id.toString)   
    def Rel(id: String) = reqt.Release(id) 
    def Rel(id: Int) = reqt.Release(id.toString) 
    def S(id: String) = reqt.Stakeholder(id) 
    def S(id: Int) = reqt.Stakeholder(id.toString) 
    def A(id: String) = reqt.Actor(id) 
    def A(id: Int) = reqt.Actor(id.toString) 
    def G(id: String) = reqt.Goal(id) 
    def G(id: Int) = reqt.Goal(id.toString) 
    def R(id: String) = reqt.Req(id)
    def R(id: Int) = reqt.Req(id.toString)
    def F(id: String) = reqt.Feature(id)   
    def F(id: Int) = reqt.Feature(id.toString)   
    def Fu(id: String) = reqt.Function(id)   
    def Fu(id: Int) = reqt.Function(id.toString)   
    def Q(id: String) = reqt.Quality(id)   
    def Q(id: Int) = reqt.Quality(id.toString)   
    def I(id: String) = reqt.Interface(id)   
    def I(id: Int) = reqt.Interface(id.toString)   
    def D(id: String) = reqt.Design(id)   
    def D(id: Int) = reqt.Design(id.toString)   
    def C(id: String) = reqt.Class(id)   
    def C(id: Int) = reqt.Class(id.toString)   
    def Me(id: String) = reqt.Member(id)   
    def Me(id: Int) = reqt.Member(id.toString)   
    def Us(id: String) = reqt.UserStory(id)  
    def Us(id: Int) = reqt.UserStory(id.toString)  
    def Uc(id: String) = reqt.UseCase(id)  
    def Uc(id: Int) = reqt.UseCase(id.toString)  
    def T(id: String) = reqt.Task(id)  
    def T(id: Int) = reqt.Task(id.toString)  
    def V(id: String) = reqt.VividScenario(id)  
    def V(id: Int) = reqt.VividScenario(id.toString)  
  }
}